version: "3"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.20.12.0/24

services:
  proxy:
    image: nginx:1.27
    restart: always
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - 80:80
      - 443:443
    links:
      - server
      - client
      
  client:
    image: ghcr.io/illgrenoble/webx-demo-client:${WEBX_VERSION:-1.2.0}
    platform: linux/amd64
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      options:
        max-size: "100m"
        max-file: "3"

  server:
    image: ghcr.io/illgrenoble/webx-demo-server:${WEBX_VERSION:-1.2.0}
    platform: linux/amd64
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "100m"
        max-file: "3"
